num1=(input('Enter number1 to calculate sum of two munmbers: '))
num2=(input('Enter number2 to calculate sum of two munmbers: '))
print ('Enterted Numbers are : '+ num1 + " ,"+ num2)
total=int(num1)+int(num2)
print('Sum of 2 numbers '+ num1+ ','+ num2 + ' is :', total)
